on: [push]
jobs:
  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    env:
      HUGO_VERSION: <Версия Hugo>

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Build
        run: hugo

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
